### ISSUE TITLE
Support for m3/h hour readings

### ISSUE THREAD

**Issue by Friggasvej** [tomaszkoperski/com.zehnder-systems.comfoconnect#3]
Hi mate,
Thanks for your great app.

Would it be possible to get the m3/h readings displayed too?
-These are shown in Hassio integration.

Thanks again ! 🙂

**Comment by tomaszkoperski** [comment]
Hi @Friggasvej
I've added this capability. Please give it a go at: https://homey.app/pl-pl/app/com.zehnder-systems.comfoconnect/Zehnder-ComfoConnect/test/
I'd appreciate if you could confirm that everything is fine before I push it to production release :)

**Comment by Friggasvej** [comment]
Works perfect, thanks 👍
