### ISSUE TITLE
Add balance mode

### ISSUE THREAD

**Issue by richie80** [tomaszkoperski/com.zehnder-systems.comfoconnect#4]
https://github.com/michaelarnauts/aiocomfoconnect
async get_balance_mode(): Get the balance mode.
async set_balance_mode(mode, timeout=-1): Set the balance mode. (balance / supply only / exhaust only)

Is it possible to add the balance mode?
(then option).

**Comment by michaelarnauts** [comment]
I don't get it. The balance mode is when you pass "balance".

**Comment by tomaszkoperski** [comment]
I've added the balance mode in [v1.1.0](https://github.com/tomaszkoperski/com.zehnder-systems.comfoconnect/releases/tag/v1.1.0)

**Comment by richie80** [comment]
I have version 1.1.0 installed on my homey but unfortunately I don't see the possible to change the ventilation mode (options: balance/supply only/extract only). 
![IMG_1207](https://user-images.githubusercontent.com/61156727/211002293-c7db70ca-ca82-4f14-aed0-6adb70737169.jpg)

**Comment by tomaszkoperski** [comment]
OK, I see what you mean. The ventilation mode can be controlled through Device -> Advanced settings and you want to do it via a "Then" flow card. I'll add that option.

**Comment by richie80** [comment]
Thank you!!

**Comment by tomaszkoperski** [comment]
@richie80 please give this version a try: https://homey.app/a/com.zehnder-systems.comfoconnect/test/
Let me know if that works well.

**Comment by richie80** [comment]
It works!
Thanks!
