### ISSUE TITLE
Bypass flow action

### ISSUE THREAD

**Issue by jenssegers** [tomaszkoperski/com.zehnder-systems.comfoconnect#8]
Hey @tomaszkoperski. I noticed that at this moment, the bypass is a setting on the device that can not be controlled by flow actions. Is there a specific reason for that?

By exposing this as a flow action, I could create a Homey flow using the outdoor/indoor temperature to automatically adjust the bypass setting to supply low-temperature air into my home for cooling.

What do you think?

**Comment by tomaszkoperski** [comment]
@jenssegers that does make sense. I myself am sticking to automatic bypass management most of the time, so I didn't really have an immediate need to add this. If there's interest - I will add this ;)

**Comment by theohendriks85** [comment]
It would also give you the opportunity to heat the house a little more on warm autumn days and reduce the number of heating hours per day. All free of charge.

Thanks

**Comment by DaaFFF1** [comment]
Are you able to add the bypass setting to the existing flows? 

That would be realy great!

**Comment by tomaszkoperski** [comment]
This has been added
